# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

from . import grpc_pb2 as grpc__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in grpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GrpcServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Command = channel.unary_unary(
            '/navigator_proto.GrpcService/Command',
            request_serializer=grpc__pb2.CommandRequest.SerializeToString,
            response_deserializer=grpc__pb2.CommandResponse.FromString,
            _registered_method=True)
        self.Heartbeat = channel.unary_unary(
            '/navigator_proto.GrpcService/Heartbeat',
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=grpc__pb2.HeartbeatPacket.FromString,
            _registered_method=True)
        self.SubscribeLogs = channel.unary_stream(
            '/navigator_proto.GrpcService/SubscribeLogs',
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=grpc__pb2.LogEntry.FromString,
            _registered_method=True)
        self.GetInterfaces = channel.unary_unary(
            '/navigator_proto.GrpcService/GetInterfaces',
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=grpc__pb2.InterfacesCollection.FromString,
            _registered_method=True)
        self.WriteInterfaces = channel.unary_unary(
            '/navigator_proto.GrpcService/WriteInterfaces',
            request_serializer=grpc__pb2.InterfacesCollection.SerializeToString,
            response_deserializer=grpc__pb2.CommandResponse.FromString,
            _registered_method=True)


class GrpcServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Command(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeLogs(self, request, context):
        """Client subscribes to receive log stream from server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInterfaces(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteInterfaces(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GrpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Command': grpc.unary_unary_rpc_method_handler(
            servicer.Command,
            request_deserializer=grpc__pb2.CommandRequest.FromString,
            response_serializer=grpc__pb2.CommandResponse.SerializeToString,
        ),
        'Heartbeat': grpc.unary_unary_rpc_method_handler(
            servicer.Heartbeat,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=grpc__pb2.HeartbeatPacket.SerializeToString,
        ),
        'SubscribeLogs': grpc.unary_stream_rpc_method_handler(
            servicer.SubscribeLogs,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=grpc__pb2.LogEntry.SerializeToString,
        ),
        'GetInterfaces': grpc.unary_unary_rpc_method_handler(
            servicer.GetInterfaces,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=grpc__pb2.InterfacesCollection.SerializeToString,
        ),
        'WriteInterfaces': grpc.unary_unary_rpc_method_handler(
            servicer.WriteInterfaces,
            request_deserializer=grpc__pb2.InterfacesCollection.FromString,
            response_serializer=grpc__pb2.CommandResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'navigator_proto.GrpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('navigator_proto.GrpcService', rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class GrpcService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Command(request,
                target,
                options=(),
                channel_credentials=None,
                call_credentials=None,
                insecure=False,
                compression=None,
                wait_for_ready=None,
                timeout=None,
                metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/navigator_proto.GrpcService/Command',
            grpc__pb2.CommandRequest.SerializeToString,
            grpc__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
                  target,
                  options=(),
                  channel_credentials=None,
                  call_credentials=None,
                  insecure=False,
                  compression=None,
                  wait_for_ready=None,
                  timeout=None,
                  metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/navigator_proto.GrpcService/Heartbeat',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            grpc__pb2.HeartbeatPacket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeLogs(request,
                      target,
                      options=(),
                      channel_credentials=None,
                      call_credentials=None,
                      insecure=False,
                      compression=None,
                      wait_for_ready=None,
                      timeout=None,
                      metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/navigator_proto.GrpcService/SubscribeLogs',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            grpc__pb2.LogEntry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInterfaces(request,
                      target,
                      options=(),
                      channel_credentials=None,
                      call_credentials=None,
                      insecure=False,
                      compression=None,
                      wait_for_ready=None,
                      timeout=None,
                      metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/navigator_proto.GrpcService/GetInterfaces',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            grpc__pb2.InterfacesCollection.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteInterfaces(request,
                        target,
                        options=(),
                        channel_credentials=None,
                        call_credentials=None,
                        insecure=False,
                        compression=None,
                        wait_for_ready=None,
                        timeout=None,
                        metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/navigator_proto.GrpcService/WriteInterfaces',
            grpc__pb2.InterfacesCollection.SerializeToString,
            grpc__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
