# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

from . import grpc_pb2 as grpc__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in grpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GrpcServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.command = channel.unary_unary(
            '/navigator_proto.GrpcService/command',
            request_serializer=grpc__pb2.CommandRequest.SerializeToString,
            response_deserializer=grpc__pb2.CommandResponse.FromString,
            _registered_method=True)
        self.heartbeat = channel.unary_unary(
            '/navigator_proto.GrpcService/heartbeat',
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=grpc__pb2.HeartbeatPacket.FromString,
            _registered_method=True)
        self.subscribe_logs = channel.unary_stream(
            '/navigator_proto.GrpcService/subscribe_logs',
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=grpc__pb2.LogEntry.FromString,
            _registered_method=True)


class GrpcServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def command(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def subscribe_logs(self, request, context):
        """Client subscribes to receive log stream from server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GrpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'command': grpc.unary_unary_rpc_method_handler(
            servicer.command,
            request_deserializer=grpc__pb2.CommandRequest.FromString,
            response_serializer=grpc__pb2.CommandResponse.SerializeToString,
        ),
        'heartbeat': grpc.unary_unary_rpc_method_handler(
            servicer.heartbeat,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=grpc__pb2.HeartbeatPacket.SerializeToString,
        ),
        'subscribe_logs': grpc.unary_stream_rpc_method_handler(
            servicer.subscribe_logs,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=grpc__pb2.LogEntry.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'navigator_proto.GrpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('navigator_proto.GrpcService', rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class GrpcService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def command(request,
                target,
                options=(),
                channel_credentials=None,
                call_credentials=None,
                insecure=False,
                compression=None,
                wait_for_ready=None,
                timeout=None,
                metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/navigator_proto.GrpcService/command',
            grpc__pb2.CommandRequest.SerializeToString,
            grpc__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def heartbeat(request,
                  target,
                  options=(),
                  channel_credentials=None,
                  call_credentials=None,
                  insecure=False,
                  compression=None,
                  wait_for_ready=None,
                  timeout=None,
                  metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/navigator_proto.GrpcService/heartbeat',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            grpc__pb2.HeartbeatPacket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def subscribe_logs(request,
                       target,
                       options=(),
                       channel_credentials=None,
                       call_credentials=None,
                       insecure=False,
                       compression=None,
                       wait_for_ready=None,
                       timeout=None,
                       metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/navigator_proto.GrpcService/subscribe_logs',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            grpc__pb2.LogEntry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
