# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'grpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\ngrpc.proto\x12\x0fnavigator_proto\x1a\x1bgoogle/protobuf/empty.proto\"!\n\x0e\x43ommandRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\"F\n\x0f\x43ommandResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"$\n\x0fHeartbeatPacket\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\".\n\x08LogEntry\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x0f\n\x07message\x18\x02 \x01(\t2\xe9\x01\n\x0bGrpcService\x12L\n\x07\x63ommand\x12\x1f.navigator_proto.CommandRequest\x1a .navigator_proto.CommandResponse\x12\x45\n\theartbeat\x12\x16.google.protobuf.Empty\x1a .navigator_proto.HeartbeatPacket\x12\x45\n\x0esubscribe_logs\x12\x16.google.protobuf.Empty\x1a\x19.navigator_proto.LogEntry0\x01\x42\x18\xaa\x02\x15NavigatorEditor.Protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'\252\002\025NavigatorEditor.Proto'
    _globals['_COMMANDREQUEST']._serialized_start = 60
    _globals['_COMMANDREQUEST']._serialized_end = 93
    _globals['_COMMANDRESPONSE']._serialized_start = 95
    _globals['_COMMANDRESPONSE']._serialized_end = 165
    _globals['_HEARTBEATPACKET']._serialized_start = 167
    _globals['_HEARTBEATPACKET']._serialized_end = 203
    _globals['_LOGENTRY']._serialized_start = 205
    _globals['_LOGENTRY']._serialized_end = 251
    _globals['_GRPCSERVICE']._serialized_start = 254
    _globals['_GRPCSERVICE']._serialized_end = 487
# @@protoc_insertion_point(module_scope)
