name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - qodana

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: List all environments including venv
        run: |
          echo "Listing all environments (including venv) in the workspace:"
          ls -al
          if [ -d "venv" ]; then
            echo "Found venv directory:"
            ls -al venv
          fi
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2025.2
        with:
          pr-mode: true
          args: |
            --linter,jetbrains/qodana-python-community:2025.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_1086752108 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'
