name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - ci/qodana-manual-trigger

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: Set up Python 3.14
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2025.2
        with:
          pr-mode: true
          args: |
            --linter,jetbrains/qodana-python-community:2025.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_1086752108 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'
