name: sync_game_activity

on:
  schedule:
    - cron: '30 20 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write


jobs:
  sync-activities:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout activities repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            module/activities/
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r module/activities/requirements-activity-updater.txt
      - name: Run activity updater
        run: python3 module/activities/activity_updater.py
      - name: Upload update log as artifact
        uses: actions/upload-artifact@v4
        with:
          name: activity-update-log
          path: module/activities/activity_update_log.md
      - name: Copy updated activity.json if changed
        if: success() && (hashFiles('module/activities/tmp_activity.json') != '')
        # Only upload and create PR if any new updates to the existing activity data
        run: cp module/activities/tmp_activity.json module/activities/activity.json
      - name: Set the output log as PR body
        if: success() && (hashFiles('module/activities/tmp_activity.json') != '')
        id: pr_body
        run: |
          echo "body<<EOF" >> $GITHUB_OUTPUT
          cat module/activities/activity_update_log.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Create Pull Request if updated
        if: success() && (hashFiles('module/activities/tmp_activity.json') != '')
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore(activity): sync activity.json (auto-update by workflow)"
          title: "CI/sync activity.json (auto-update by workflow)"
          body: "${{ steps.pr_body.outputs.body }}"
          branch: "auto-sync-activity"
          reviewers: |
            Nanboom233
            shenxian66ya
            beihaihaihai
